services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/kosmopay.ru/fullchain.pem:/etc/nginx/ssl/app/fullchain.pem
      - /etc/letsencrypt/live/kosmopay.ru/privkey.pem:/etc/nginx/ssl/app/privkey.pem
      - /etc/letsencrypt/live/api.kosmopay.ru/fullchain.pem:/etc/nginx/ssl/api/fullchain.pem
      - /etc/letsencrypt/live/api.kosmopay.ru/privkey.pem:/etc/nginx/ssl/api/privkey.pem
    networks:
      - network

networks:
  network:
    driver: bridge
